/**
 * WooCommerce Customers Vocabulary Entry (Canonical Source)
 *
 * Community-contributable vocabulary data for WooCommerce customers.
 * Conforms to the VocabularyEntry interface defined in ../vocabulary-types.ts
 */

import type { VocabularyEntry } from '../../vocabulary-types';

const SCHEMA_NS = 'https://schema.org/';

export const woocommerceCustomers: VocabularyEntry = {
  connector_type: 'woocommerce',
  sync_entity: 'customers',
  version: '1.0.0',
  last_verified: '2025-01-15T00:00:00.000Z',
  template_slug: 'woocommerce',
  canonical_type_uri: `${SCHEMA_NS}Person`,
  confidence_override: 'verified',
  confidence_score: 0.95,
  description: 'WooCommerce customers representing registered users with billing information and order history.',
  json_schema: {
    $schema: 'http://json-schema.org/draft-07/schema#',
    type: 'object',
    required: ['id', 'email', 'first_name', 'last_name'],
    properties: {
      id: { type: 'number', description: 'Unique customer identifier' },
      email: { type: 'string', format: 'email', description: 'Customer email address' },
      first_name: { type: 'string', description: 'Customer first name' },
      last_name: { type: 'string', description: 'Customer last name' },
      date_created: { type: 'string', format: 'date-time', description: 'ISO 8601 timestamp of customer registration' },
      billing: {
        type: 'object',
        description: 'Customer billing address and contact details',
        properties: {
          first_name: { type: 'string' },
          last_name: { type: 'string' },
          company: { type: 'string' },
          address_1: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          postcode: { type: 'string' },
          country: { type: 'string' },
          email: { type: 'string', format: 'email' },
          phone: { type: 'string' },
        },
      },
    },
  },
  fields: [
    {
      name: 'id',
      type: 'number',
      required: true,
      description: 'Unique customer identifier',
      canonical_property_uri: `${SCHEMA_NS}identifier`,
    },
    {
      name: 'email',
      type: 'string',
      required: true,
      description: 'Customer email address',
      canonical_property_uri: `${SCHEMA_NS}email`,
      format: 'email',
    },
    {
      name: 'first_name',
      type: 'string',
      required: true,
      description: 'Customer first name',
      canonical_property_uri: `${SCHEMA_NS}givenName`,
    },
    {
      name: 'last_name',
      type: 'string',
      required: true,
      description: 'Customer last name',
      canonical_property_uri: `${SCHEMA_NS}familyName`,
    },
    {
      name: 'date_created',
      type: 'string',
      required: false,
      description: 'ISO 8601 timestamp of customer registration',
      canonical_property_uri: `${SCHEMA_NS}dateCreated`,
      format: 'date-time',
    },
    {
      name: 'billing',
      type: 'object',
      required: false,
      description: 'Customer billing address and contact details',
      canonical_property_uri: null,
      parent_path: 'customer',
    },
  ],
  validation_rules: [
    {
      rule_id: 'woocommerce-customers-id-required',
      description: 'Customer ID must be present',
      severity: 'warning',
      constraint: { required: ['id'] },
      target_fields: ['id'],
    },
    {
      rule_id: 'woocommerce-customers-email-required',
      description: 'Customer email must be present',
      severity: 'warning',
      constraint: { required: ['email'] },
      target_fields: ['email'],
    },
    {
      rule_id: 'woocommerce-customers-email-format',
      description: 'Customer email must be a valid email address',
      severity: 'warning',
      constraint: { properties: { email: { format: 'email' } } },
      target_fields: ['email'],
    },
    {
      rule_id: 'woocommerce-customers-first-name-required',
      description: 'Customer first name must be present',
      severity: 'warning',
      constraint: { required: ['first_name'] },
      target_fields: ['first_name'],
    },
    {
      rule_id: 'woocommerce-customers-last-name-required',
      description: 'Customer last name must be present',
      severity: 'warning',
      constraint: { required: ['last_name'] },
      target_fields: ['last_name'],
    },
  ],
  transformation_template: {
    steps: [
      {
        order: 0,
        transform_type: 'rename-field',
        operation_config: {
          mappings: {
            first_name: 'givenName',
            last_name: 'familyName',
            date_created: 'dateCreated',
          },
        },
        description: 'Rename WooCommerce customer fields to schema.org canonical property names',
      },
      {
        order: 1,
        transform_type: 'format-timestamp',
        operation_config: {
          fields: ['dateCreated'],
          input_format: 'ISO8601',
          output_format: 'ISO8601',
        },
        description: 'Normalize dateCreated timestamp to consistent ISO 8601 format',
      },
      {
        order: 2,
        transform_type: 'flatten',
        operation_config: {
          field: 'billing',
          prefix: 'billing_',
          fields_to_extract: ['first_name', 'last_name', 'company', 'address_1', 'city', 'state', 'postcode', 'country', 'email', 'phone'],
        },
        description: 'Flatten nested billing object into top-level fields with billing_ prefix',
      },
      {
        order: 3,
        transform_type: 'select-fields',
        operation_config: {
          fields: [
            'id',
            'email',
            'givenName',
            'familyName',
            'dateCreated',
            'billing_first_name',
            'billing_last_name',
            'billing_company',
            'billing_address_1',
            'billing_city',
            'billing_state',
            'billing_postcode',
            'billing_country',
            'billing_email',
            'billing_phone',
          ],
        },
        description: 'Select only mapped fields for the canonical output',
      },
    ],
    sample_input: [
      {
        id: 12,
        email: 'sarah@example.com',
        first_name: 'Sarah',
        last_name: 'Connor',
        date_created: '2024-03-15T10:00:00',
        billing: { first_name: 'Sarah', last_name: 'Connor', company: 'Cyberdyne', address_1: '100 Elm St', city: 'Austin', state: 'TX', postcode: '73301', country: 'US', email: 'sarah@example.com', phone: '+1-555-100-2000' },
      },
      {
        id: 8,
        email: 'mike@example.com',
        first_name: 'Mike',
        last_name: 'Chen',
        date_created: '2024-06-20T14:30:00',
        billing: { first_name: 'Mike', last_name: 'Chen', company: '', address_1: '200 Oak Dr', city: 'Denver', state: 'CO', postcode: '80201', country: 'US', email: 'mike@example.com', phone: '+1-555-200-3000' },
      },
      {
        id: 25,
        email: 'emma@example.com',
        first_name: 'Emma',
        last_name: 'Dubois',
        date_created: '2025-01-05T08:00:00',
        billing: { first_name: 'Emma', last_name: 'Dubois', company: 'Maison Dubois', address_1: '50 Rue de Paris', city: 'Lyon', state: '', postcode: '69001', country: 'FR', email: 'emma@example.com', phone: '+33-4-7200-0000' },
      },
    ],
    expected_output: [
      {
        id: 12,
        email: 'sarah@example.com',
        givenName: 'Sarah',
        familyName: 'Connor',
        dateCreated: '2024-03-15T10:00:00',
        billing_first_name: 'Sarah',
        billing_last_name: 'Connor',
        billing_company: 'Cyberdyne',
        billing_address_1: '100 Elm St',
        billing_city: 'Austin',
        billing_state: 'TX',
        billing_postcode: '73301',
        billing_country: 'US',
        billing_email: 'sarah@example.com',
        billing_phone: '+1-555-100-2000',
      },
      {
        id: 8,
        email: 'mike@example.com',
        givenName: 'Mike',
        familyName: 'Chen',
        dateCreated: '2024-06-20T14:30:00',
        billing_first_name: 'Mike',
        billing_last_name: 'Chen',
        billing_company: '',
        billing_address_1: '200 Oak Dr',
        billing_city: 'Denver',
        billing_state: 'CO',
        billing_postcode: '80201',
        billing_country: 'US',
        billing_email: 'mike@example.com',
        billing_phone: '+1-555-200-3000',
      },
      {
        id: 25,
        email: 'emma@example.com',
        givenName: 'Emma',
        familyName: 'Dubois',
        dateCreated: '2025-01-05T08:00:00',
        billing_first_name: 'Emma',
        billing_last_name: 'Dubois',
        billing_company: 'Maison Dubois',
        billing_address_1: '50 Rue de Paris',
        billing_city: 'Lyon',
        billing_state: '',
        billing_postcode: '69001',
        billing_country: 'FR',
        billing_email: 'emma@example.com',
        billing_phone: '+33-4-7200-0000',
      },
    ],
  },
  relationships: [],
};
