/**
 * WooCommerce Orders Vocabulary Entry (Canonical Source)
 *
 * Community-contributable vocabulary data for WooCommerce orders.
 * Conforms to the VocabularyEntry interface defined in ../vocabulary-types.ts
 */

import type { VocabularyEntry } from '../../vocabulary-types';

const SCHEMA_NS = 'https://schema.org/';

export const woocommerceOrders: VocabularyEntry = {
  connector_type: 'woocommerce',
  sync_entity: 'orders',
  version: '1.0.0',
  last_verified: '2025-01-15T00:00:00.000Z',
  template_slug: 'woocommerce',
  canonical_type_uri: `${SCHEMA_NS}Order`,
  confidence_override: 'verified',
  confidence_score: 0.95,
  description: 'WooCommerce orders representing customer purchases with line items, billing details, and order status.',
  json_schema: {
    $schema: 'http://json-schema.org/draft-07/schema#',
    type: 'object',
    required: ['id', 'number', 'status', 'date_created', 'total'],
    properties: {
      id: { type: 'number', description: 'Unique order identifier' },
      number: { type: 'string', description: 'Order number displayed to customer' },
      status: { type: 'string', description: 'Order status (pending, processing, on-hold, completed, cancelled, refunded, failed)' },
      date_created: { type: 'string', format: 'date-time', description: 'ISO 8601 timestamp of order creation' },
      total: { type: 'string', description: 'Total price of the order' },
      currency: { type: 'string', description: 'Three-letter ISO 4217 currency code' },
      customer_id: { type: 'number', description: 'Customer ID who placed the order (0 for guest)' },
      line_items: {
        type: 'array',
        description: 'List of line items in the order',
        items: {
          type: 'object',
          properties: {
            id: { type: 'number' },
            product_id: { type: 'number' },
            name: { type: 'string' },
            quantity: { type: 'number' },
            total: { type: 'string' },
          },
        },
      },
      billing: {
        type: 'object',
        description: 'Billing address and contact details',
        properties: {
          first_name: { type: 'string' },
          last_name: { type: 'string' },
          email: { type: 'string', format: 'email' },
          phone: { type: 'string' },
          address_1: { type: 'string' },
          city: { type: 'string' },
          state: { type: 'string' },
          postcode: { type: 'string' },
          country: { type: 'string' },
        },
      },
    },
  },
  fields: [
    {
      name: 'id',
      type: 'number',
      required: true,
      description: 'Unique order identifier',
      canonical_property_uri: `${SCHEMA_NS}identifier`,
    },
    {
      name: 'number',
      type: 'string',
      required: true,
      description: 'Order number displayed to customer',
      canonical_property_uri: `${SCHEMA_NS}orderNumber`,
    },
    {
      name: 'status',
      type: 'string',
      required: true,
      description: 'Order status (pending, processing, on-hold, completed, cancelled, refunded, failed)',
      canonical_property_uri: `${SCHEMA_NS}orderStatus`,
    },
    {
      name: 'date_created',
      type: 'string',
      required: true,
      description: 'ISO 8601 timestamp of order creation',
      canonical_property_uri: `${SCHEMA_NS}orderDate`,
      format: 'date-time',
    },
    {
      name: 'total',
      type: 'string',
      required: true,
      description: 'Total price of the order',
      canonical_property_uri: `${SCHEMA_NS}totalPrice`,
    },
    {
      name: 'currency',
      type: 'string',
      required: false,
      description: 'Three-letter ISO 4217 currency code',
      canonical_property_uri: `${SCHEMA_NS}priceCurrency`,
    },
    {
      name: 'customer_id',
      type: 'number',
      required: false,
      description: 'Customer ID who placed the order (0 for guest)',
      canonical_property_uri: `${SCHEMA_NS}customer`,
    },
    {
      name: 'line_items',
      type: 'array',
      required: false,
      description: 'List of line items in the order',
      canonical_property_uri: `${SCHEMA_NS}orderedItem`,
    },
    {
      name: 'billing',
      type: 'object',
      required: false,
      description: 'Billing address and contact details',
      canonical_property_uri: null,
      parent_path: 'order',
    },
  ],
  validation_rules: [
    {
      rule_id: 'woocommerce-orders-id-required',
      description: 'Order ID must be present',
      severity: 'warning',
      constraint: { required: ['id'] },
      target_fields: ['id'],
    },
    {
      rule_id: 'woocommerce-orders-number-required',
      description: 'Order number must be present',
      severity: 'warning',
      constraint: { required: ['number'] },
      target_fields: ['number'],
    },
    {
      rule_id: 'woocommerce-orders-date-created-format',
      description: 'date_created must be a valid ISO 8601 date-time',
      severity: 'warning',
      constraint: { properties: { date_created: { format: 'date-time' } } },
      target_fields: ['date_created'],
    },
    {
      rule_id: 'woocommerce-orders-total-type',
      description: 'total must be a string representing a decimal number',
      severity: 'warning',
      constraint: { properties: { total: { type: 'string' } } },
      target_fields: ['total'],
    },
  ],
  transformation_template: {
    steps: [
      {
        order: 0,
        transform_type: 'rename-field',
        operation_config: {
          mappings: {
            number: 'orderNumber',
            status: 'orderStatus',
            date_created: 'orderDate',
            total: 'totalPrice',
            currency: 'priceCurrency',
            customer_id: 'customerId',
          },
        },
        description: 'Rename WooCommerce order fields to schema.org canonical property names',
      },
      {
        order: 1,
        transform_type: 'format-timestamp',
        operation_config: {
          fields: ['orderDate'],
          input_format: 'ISO8601',
          output_format: 'ISO8601',
        },
        description: 'Normalize orderDate timestamp to consistent ISO 8601 format',
      },
      {
        order: 2,
        transform_type: 'flatten',
        operation_config: {
          field: 'billing',
          prefix: 'billing_',
          fields_to_extract: ['first_name', 'last_name', 'email', 'phone', 'address_1', 'city', 'state', 'postcode', 'country'],
        },
        description: 'Flatten nested billing object into top-level fields with billing_ prefix',
      },
      {
        order: 3,
        transform_type: 'select-fields',
        operation_config: {
          fields: [
            'id',
            'orderNumber',
            'orderStatus',
            'orderDate',
            'totalPrice',
            'priceCurrency',
            'customerId',
            'line_items',
            'billing_first_name',
            'billing_last_name',
            'billing_email',
            'billing_phone',
            'billing_address_1',
            'billing_city',
            'billing_state',
            'billing_postcode',
            'billing_country',
          ],
        },
        description: 'Select only mapped fields for the canonical output',
      },
    ],
    sample_input: [
      {
        id: 1024,
        number: '1024',
        status: 'processing',
        date_created: '2025-01-10T14:30:00',
        total: '89.97',
        currency: 'USD',
        customer_id: 12,
        line_items: [
          { id: 1, product_id: 93, name: 'Organic Green Tea', quantity: 3, total: '44.97' },
          { id: 2, product_id: 107, name: 'Ceramic Mug Set', quantity: 1, total: '45.00' },
        ],
        billing: { first_name: 'Sarah', last_name: 'Connor', email: 'sarah@example.com', phone: '+1-555-100-2000', address_1: '100 Elm St', city: 'Austin', state: 'TX', postcode: '73301', country: 'US' },
      },
      {
        id: 1025,
        number: '1025',
        status: 'completed',
        date_created: '2025-01-11T09:00:00',
        total: '150.00',
        currency: 'USD',
        customer_id: 8,
        line_items: [
          { id: 3, product_id: 45, name: 'Wireless Headphones', quantity: 1, total: '150.00' },
        ],
        billing: { first_name: 'Mike', last_name: 'Chen', email: 'mike@example.com', phone: '+1-555-200-3000', address_1: '200 Oak Dr', city: 'Denver', state: 'CO', postcode: '80201', country: 'US' },
      },
      {
        id: 1026,
        number: '1026',
        status: 'pending',
        date_created: '2025-01-12T16:45:00',
        total: '32.50',
        currency: 'EUR',
        customer_id: 0,
        line_items: [
          { id: 4, product_id: 201, name: 'Notebook Journal', quantity: 2, total: '25.00' },
          { id: 5, product_id: 202, name: 'Ballpoint Pen', quantity: 3, total: '7.50' },
        ],
        billing: { first_name: 'Guest', last_name: 'Buyer', email: 'guest@example.com', phone: '', address_1: '50 Rue de Paris', city: 'Lyon', state: '', postcode: '69001', country: 'FR' },
      },
    ],
    expected_output: [
      {
        id: 1024,
        orderNumber: '1024',
        orderStatus: 'processing',
        orderDate: '2025-01-10T14:30:00',
        totalPrice: '89.97',
        priceCurrency: 'USD',
        customerId: 12,
        line_items: [
          { id: 1, product_id: 93, name: 'Organic Green Tea', quantity: 3, total: '44.97' },
          { id: 2, product_id: 107, name: 'Ceramic Mug Set', quantity: 1, total: '45.00' },
        ],
        billing_first_name: 'Sarah',
        billing_last_name: 'Connor',
        billing_email: 'sarah@example.com',
        billing_phone: '+1-555-100-2000',
        billing_address_1: '100 Elm St',
        billing_city: 'Austin',
        billing_state: 'TX',
        billing_postcode: '73301',
        billing_country: 'US',
      },
      {
        id: 1025,
        orderNumber: '1025',
        orderStatus: 'completed',
        orderDate: '2025-01-11T09:00:00',
        totalPrice: '150.00',
        priceCurrency: 'USD',
        customerId: 8,
        line_items: [
          { id: 3, product_id: 45, name: 'Wireless Headphones', quantity: 1, total: '150.00' },
        ],
        billing_first_name: 'Mike',
        billing_last_name: 'Chen',
        billing_email: 'mike@example.com',
        billing_phone: '+1-555-200-3000',
        billing_address_1: '200 Oak Dr',
        billing_city: 'Denver',
        billing_state: 'CO',
        billing_postcode: '80201',
        billing_country: 'US',
      },
      {
        id: 1026,
        orderNumber: '1026',
        orderStatus: 'pending',
        orderDate: '2025-01-12T16:45:00',
        totalPrice: '32.50',
        priceCurrency: 'EUR',
        customerId: 0,
        line_items: [
          { id: 4, product_id: 201, name: 'Notebook Journal', quantity: 2, total: '25.00' },
          { id: 5, product_id: 202, name: 'Ballpoint Pen', quantity: 3, total: '7.50' },
        ],
        billing_first_name: 'Guest',
        billing_last_name: 'Buyer',
        billing_email: 'guest@example.com',
        billing_phone: '',
        billing_address_1: '50 Rue de Paris',
        billing_city: 'Lyon',
        billing_state: '',
        billing_postcode: '69001',
        billing_country: 'FR',
      },
    ],
  },
  relationships: [
    {
      source_field: 'customer_id',
      target_entity_type: 'customers',
      relationship_uri: `${SCHEMA_NS}customer`,
      cardinality: 'one-to-one',
    },
    {
      source_field: 'line_items',
      target_entity_type: 'products',
      relationship_uri: `${SCHEMA_NS}orderedItem`,
      cardinality: 'one-to-many',
    },
  ],
};
